### ISSUE TITLE
Automated tests with Travis

### ISSUE THREAD

**Issue by davecap** [solvebio/veppy#7]
Add automatic tests with Travis when pushing to any branch.

**Comment by surajnarwade** [comment]
I would like to work on this

**Comment by jsh2134** [comment]
hey @surajnarwade awesome!

there a few issues with #8 but I just merged it in so that travis would build. you'll notice that it failed 👎  because interval tree was not installed

things to look into
- [ ] install the package first! in the install section you will want to add `python setup.py install`
- [ ] download the data onto travis using the instructions in the README
- [ ] fix the file indentation using a travis linter
- [ ] run tests in python 3 versions! (see https://docs.travis-ci.com/user/languages/python/)
- [ ] cache the data for faster builds! (see https://docs.travis-ci.com/user/caching/)
- [ ] add travis build widget (https://docs.travis-ci.com/user/status-images/)
- [ ] add yourself to the AUTHORS file!

**Comment by surajnarwade** [comment]
@jsh2134 thanks I am onto it, can you please add 'hacktoberfest' label to issue if you don't mind :)

**Comment by davecap** [comment]
Also, see https://github.com/solvebio/solvebio-python/blob/master/.travis.yml as an example (ignore the notifications section). Instead of installing the package in travis, it might be enough to run the nosetests through `python setup.py nosetests` (see: http://nose.readthedocs.io/en/latest/api/commands.html)

**Comment by surajnarwade** [comment]
@jsh2134 , why there is need to download data onto travis ?

**Comment by jsh2134** [comment]
veppy requires genomic data in order to run effect predictions, otherwise the package doesn't work. 

the README describes how to do this https://github.com/solvebio/veppy/blob/master/README.rst#setup
